export interface GhabashiMenuItem {
  id: number
  nameEn: string
  nameAr: string
  catEn: string
  catAr: string
  sizeEn: string
  sizeAr: string
  price: number
  descEn: string
  descAr: string
  addEn: string
  addAr: string
  img: string
  available: boolean
}

export interface GhabashiCategory {
  nameEn: string
  nameAr: string
}

export const GHABASHI_CATEGORIES: GhabashiCategory[] = [
  { nameEn: 'Gathering Box',       nameAr: 'بوكس الجمعات' },
  { nameEn: 'Meals',               nameAr: 'وجبات' },
  { nameEn: 'Sandwiches And Chips', nameAr: 'ساندوتش و شيبس' },
  { nameEn: 'Sandwiches',          nameAr: 'ساندويتشات' },
  { nameEn: 'Ciabatta & Salad',    nameAr: 'شيباتا و سلط' },
  { nameEn: 'Eggs And Kebda',      nameAr: 'بيض و كبدة' },
  { nameEn: 'Pies',                nameAr: 'الفطائر' },
  { nameEn: 'Side Orders',         nameAr: 'الطلبات الجانبية' },
  { nameEn: 'Drinks',              nameAr: 'المشروبات' },
]

export const GHABASHI_MENU: GhabashiMenuItem[] = [
  { id: 1,  nameEn: 'Mix Box',                        nameAr: 'مكس بوكس',                            catEn: 'Gathering Box',        catAr: 'بوكس الجمعات',         sizeEn: 'Box',       sizeAr: 'بوكس',          price: 44, available: true, descEn: "12 half sandwiches — choose between egg, liver, tuna, halloumi or za'atar", descAr: 'بوكس يحتوي على انصاص ساندوتش ١٢ قطعة اختر مابين بيض - كبدة - تونا - حلومي - زعتر', addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/80788656?width=400&quality=80' },
  { id: 2,  nameEn: 'Gathering Box',                  nameAr: 'بوكس الجمعات',                        catEn: 'Gathering Box',        catAr: 'بوكس الجمعات',         sizeEn: 'Box',       sizeAr: 'بوكس',          price: 74, available: true, descEn: 'Selection box for 4-6 people — tuna, turkey, halloumi, labnah options',           descAr: 'بوكس جمعات مناسب ٤-٦ اشخاص من اختيارك تونا - تركي - حلومي - لبنة',            addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/100737/product/65492980/a205c036-5bd1-4222-bfb6-99a8b8020c4d.jpg?width=400&quality=80' },
  { id: 3,  nameEn: 'Club Sandwich Box',              nameAr: 'بوكس كلوب ساندويتش',                 catEn: 'Gathering Box',        catAr: 'بوكس الجمعات',         sizeEn: 'Box',       sizeAr: 'بوكس',          price: 49, available: true, descEn: '8 chicken club sandwich quarters with crispy chips',                              descAr: 'بوكس كلوب دجاج ساندوتش ٨ قطع مع شيبس مقرمش',                                  addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/100737/product/106309875/5c7ab3ee-2145-481c-bc91-693851cd8e36.jpg?width=400&quality=80' },
  { id: 4,  nameEn: 'Mini Box',                       nameAr: 'ميني بوكس',                           catEn: 'Gathering Box',        catAr: 'بوكس الجمعات',         sizeEn: 'Box',       sizeAr: 'بوكس',          price: 44, available: true, descEn: "10 mini samoli: halloumi, tuna, fried egg, boiled egg, za'atar",                   descAr: 'بوكس مناسب لجمعه عبارت عن ١٠ ميني صامولي: حلومي - تونا - بيض مقلي - بيض مسلوق - زعتر', addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/84911/product/2edbe42d-509d-4443-8736-06f3db0b71ad.jpg?width=400&quality=80' },
  { id: 5,  nameEn: 'Sharing Meal',                   nameAr: 'وجبة المشاركة',                       catEn: 'Meals',                catAr: 'وجبات',                sizeEn: 'Meal',      sizeAr: 'وجبة',          price: 33, available: true, descEn: 'A meal for two — choose from halloumi, tuna or cheesy turkey options',             descAr: 'وجبة مناسبة لشخصين من اختيارك حلومي - تونا - تشيزي تركي',                      addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/84505737?width=400&quality=80' },
  { id: 6,  nameEn: 'Steak & Egg',                    nameAr: 'ستيك و بيض',                          catEn: 'Meals',                catAr: 'وجبات',                sizeEn: 'Meal',      sizeAr: 'وجبة',          price: 30, available: true, descEn: '140g beef, cheese, fries, eggs and house sauce — for 1 person',                   descAr: '١٤٠جم لحم بقري - جبن - بطاطس - بيض - صوص خاص - لشخص واحد',                   addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/100737/PRODUCT/97729191/374a607d-9178-4f18-8b91-e492af328f8e.jpg?width=400&quality=80' },
  { id: 7,  nameEn: 'Philly & Grilled Chicken & Fries', nameAr: 'فيلي و تشكين جريل و بطاطس',        catEn: 'Meals',                catAr: 'وجبات',                sizeEn: 'Meal',      sizeAr: 'وجبة',          price: 29, available: true, descEn: 'Combo: Philly cheesesteak and grilled chicken with fries',                        descAr: 'عرض: فيلي تشيزستيك و تشكين جريل مع بطاطس',                                    addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492898?width=400&quality=80' },
  { id: 8,  nameEn: 'Breakfast Meal',                 nameAr: 'وجبة فطورك',                          catEn: 'Meals',                catAr: 'وجبات',                sizeEn: 'Meal',      sizeAr: 'وجبة',          price: 1,  available: true, descEn: 'All-day breakfast — egg, avocado, turkey, shakshuka or liver options',             descAr: 'فطور طوال اليوم - عدة خيارات: بيض - افوكادو - تركي - شكشوكة - كبدة',           addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/PRODUCT/c0df0ab4-5c6a-4d38-a796-643e73e43912.jpg?width=400&quality=80' },
  { id: 9,  nameEn: 'Chicken Club Sandwich',          nameAr: 'دجاج كلوب ساندوتش',                  catEn: 'Sandwiches And Chips', catAr: 'ساندوتش و شيبس',       sizeEn: 'Set',       sizeAr: 'ست',            price: 23, available: true, descEn: 'Lettuce, cheese, avocado, tomato, egg and grilled chicken with chipotle sauce and chips', descAr: 'خس - جبن - افوكادو - طماطم - بيض - دجاج مشوي مع صوص شيبوتلي و شيبس',        addEn: 'Extra Avocado, Extra Cheese',        addAr: 'زيادة افوكادو، زيادة جبن',              img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/84911/product/95151132/d0726a03-eb3e-4221-84fa-4e62fb1814ca.jpg?width=400&quality=80' },
  { id: 10, nameEn: 'Turkey Club Sandwich',           nameAr: 'تيركي كلوب ساندوتش',                 catEn: 'Sandwiches And Chips', catAr: 'ساندوتش و شيبس',       sizeEn: 'Set',       sizeAr: 'ست',            price: 23, available: true, descEn: 'Turkey slices, avocado, egg mix, lettuce, tomato with chipotle sauce and chips',   descAr: 'شرائح تيركي - افوكادو - خلطة بيض - خس - طماطم مع صوص شيبوتلي و شيبس',       addEn: 'Extra Avocado, Extra Turkey',        addAr: 'زيادة افوكادو، زيادة تيركي',           img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/84911/PRODUCT/eac51611-a95d-464b-a8a4-28cf21e8737b.jpg?width=400&quality=80' },
  { id: 11, nameEn: 'Egg Club Sandwich',              nameAr: 'بيض كلوب ساندوتش',                   catEn: 'Sandwiches And Chips', catAr: 'ساندوتش و شيبس',       sizeEn: 'Set',       sizeAr: 'ست',            price: 23, available: true, descEn: 'Scrambled egg, turkey, avocado, arugula, tomato with special sauce and chips',    descAr: 'بيض سكرامبل - تيركي - افوكادو - جرجير - طماطم مع صوص خاص و شيبس',            addEn: 'Extra Egg, Extra Avocado',           addAr: 'زيادة بيض، زيادة افوكادو',             img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/PRODUCT/91784c3e-b209-46d5-9c23-46cea6f527c8.jpg?width=400&quality=80' },
  { id: 12, nameEn: 'Halloumi Egg Club Sandwich',     nameAr: 'حلومي بيض كلوب ساندوتش',             catEn: 'Sandwiches And Chips', catAr: 'ساندوتش و شيبس',       sizeEn: 'Set',       sizeAr: 'ست',            price: 24, available: true, descEn: 'Halloumi, egg salad, avocado, sun-dried tomato with special sauce and chips',     descAr: 'حلومي - سلطة بيض - افوكادو - طماطم مجففة مع صوص خاص و شيبس',                 addEn: 'Extra Halloumi, Extra Avocado',      addAr: 'زيادة حلومي، زيادة افوكادو',           img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/84911/product/3001b23f-8027-48d9-81e4-7f5993f5e1c9.jpg?width=400&quality=80' },
  { id: 13, nameEn: 'Grill Chicken',                  nameAr: 'جريل تشيكن',                          catEn: 'Sandwiches',           catAr: 'ساندويتشات',           sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 14, available: true, descEn: 'Grilled chicken with sauce and cheese',                                           descAr: 'دجاج مشوي - صوص - جبن',                                                        addEn: 'Extra Sauce, Extra Cheese',          addAr: 'زيادة صوص، زيادة جبن',                 img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/94684017/c77dd7a8-45af-4f60-924a-56c27a2033dd.jpg?width=400&quality=80' },
  { id: 14, nameEn: 'Philly Cheesesteak',             nameAr: 'فيلي ستيك',                           catEn: 'Sandwiches',           catAr: 'ساندويتشات',           sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 13, available: true, descEn: 'Beef sandwich with cheese and Ghabashi sauce on special white bread',              descAr: 'ساندوتش لحم بقري مع الجبنة وصوص غباشي بخبز الابيض الخاص',                     addEn: 'Extra Truffle Sauce, Extra Hot Sauce, Ketchup, Extra Jalapeno, Extra Sauce, Extra Cheese', addAr: 'صوص ترافيل, شطه, كاتشاب، زيادة هالبينو، زيادة صوص، زيادة جبن', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/65492947/5b3ef645-d2af-48ad-9aed-6fb54982658e.jpg?width=400&quality=80' },
  { id: 15, nameEn: 'Cheesy Philly Steak',            nameAr: 'تشيزي فيلي ستيك',                    catEn: 'Sandwiches',           catAr: 'ساندويتشات',           sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 15, available: true, descEn: 'Double yellow cheese and mozzarella with beef, potato and onion',                  descAr: 'دبل تشيز مع موزريلا مكس مع اللحم البقري والبطاطس والبصل',                      addEn: 'Extra Truffle Sauce, Extra Hot Sauce, Extra Cheese', addAr: 'صوص ترافيل, شطه، زيادة جبن', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/65492946/5a9f6231-e7ac-42fb-9918-88d5d0c3b201.jpg?width=400&quality=80' },
  { id: 16, nameEn: 'Chicken Fillet',                 nameAr: 'تشيكن فيليه',                         catEn: 'Sandwiches',           catAr: 'ساندويتشات',           sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 13, available: true, descEn: 'Fried chicken fillet with lettuce, cheese and ranch sauce',                        descAr: 'دجاج مقلي مع الخس و الجبنة و رانش صوص',                                       addEn: 'Extra Truffle Sauce, Extra Hot Sauce, Ketchup, Extra Jalapeno', addAr: 'صوص ترافيل, شطه, كاتشاب، زيادة هالبينو', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/65492943/52bd0628-27d6-4eb3-9da0-4a7cd98a3a2b.jpg?width=400&quality=80' },
  { id: 17, nameEn: 'Egg Salad Sandwich',             nameAr: 'ساندويتش سلطة بيض',                  catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 15, available: true, descEn: 'Boiled eggs with cheddar cheese, avocado and sun-dried tomatoes',                 descAr: 'خلطة بيض المسلوق مع جبن شيدر و افوكادو وطماطم مجففة',                          addEn: 'Extra Avocado, Extra Cheese',        addAr: 'زيادة افوكادو، زيادة جبن',              img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/90222271/ed50a3cf-f592-4bf5-bde0-542d97532797.jpg?width=400&quality=80' },
  { id: 18, nameEn: 'Tuna Ciabatta',                  nameAr: 'تونا شيباتا',                         catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Ciabatta',  sizeAr: 'شيباتا',        price: 14, available: true, descEn: 'Tuna, avocado, pesto, lettuce, tomato',                                           descAr: 'تونا - افوكادو - بيستو - خس - طماطم',                                          addEn: 'Extra Sauce, Extra Rocca, Extra Avocado', addAr: 'صوص، جرجير، افوكادو',           img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/65492938/f8ff9ada-4774-40a1-bc72-3eead79e51b2.jpg?width=400&quality=80' },
  { id: 19, nameEn: 'Spicy Tuna Ciabatta',            nameAr: 'سبايسي تونا شيباتا',                 catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Ciabatta',  sizeAr: 'شيباتا',        price: 15, available: true, descEn: 'Tuna, cheese, jalapeño, tabasco, tomato, avocado, lettuce, pesto',                descAr: 'تونا - هالبينو - تباسكو - طماطم - افوكادو - خس - بيستو',                      addEn: 'Extra Sauce, Extra Rocca, Extra Avocado, Cheese, Spicy', addAr: 'صوص، جرجير، افوكادو, جبن، سبايسي', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/a0d806b4-89fa-41b2-b41f-a839a5751d16.jpg?width=400&quality=80' },
  { id: 20, nameEn: 'Halloumi Ciabatta',              nameAr: 'حلومي شيباتا',                        catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Ciabatta',  sizeAr: 'شيباتا',        price: 14, available: true, descEn: "Halloumi, sun-dried tomato, arugula, olives, pesto, za'atar labneh",               descAr: 'حلومي - طماطم مجفف - جرجير - زيتون - بيستو - خلطة زعتر لبنه',                addEn: 'Extra Sauce, Extra Rocca, Extra Avocado, Cheese, Pesto, Spicy', addAr: 'صوص، جرجير، افوكادو, جبن، بيستو، سبايسي', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/d5a48a2a-7cc4-45f3-ab63-127236b813d5.jpg?width=400&quality=80' },
  { id: 21, nameEn: 'Chicken Ciabatta',               nameAr: 'تشكين شيباتا',                        catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Ciabatta',  sizeAr: 'شيباتا',        price: 18, available: true, descEn: 'Chicken salad, arugula, tomato and pesto on ciabatta',                            descAr: 'خلطة دجاج سلط - جرجير - طماطم - بيستو على خبز شيباتا',                        addEn: 'Extra Pesto, Extra Chicken',         addAr: 'زيادة بيستو، زيادة دجاج',              img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/52fd5482-06a4-4ef2-ac4b-975aae655f42.jpg?width=400&quality=80' },
  { id: 22, nameEn: 'Cheesy Turkey Ciabatta',         nameAr: 'تشيزي تركي شيباتا',                  catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Ciabatta',  sizeAr: 'شيباتا',        price: 15, available: true, descEn: 'Turkey slices, cheddar, mozzarella, pesto, arugula, special sauce',               descAr: 'شرائح تركي - جبن شيدر - جبن موزريلا - بيستو - جرجير - صوص الخاص',             addEn: 'Extra Sauce, Extra Rocca, Extra Avocado, Cheese, Pesto, Spicy', addAr: 'صوص، جرجير، افوكادو, جبن، بيستو، سبايسي', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/112655262/7e80b68d-9642-40f9-a71a-ea308cf2967a.jpg?width=400&quality=80' },
  { id: 23, nameEn: 'Halloumi Salad',                 nameAr: 'حلومي سلط',                           catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Salad',     sizeAr: 'سلطة',          price: 24, available: true, descEn: 'Halloumi with sun-dried tomato, served with rocca salad and chips',                descAr: 'حلومي - طماطم مجفف - مع سلطة روكا و شيبس',                                    addEn: 'Extra Halloumi, Extra Rocca',        addAr: 'زيادة حلومي، زيادة جرجير',             img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/product/1f4060f9-1b2d-4a1d-8882-5eb111856ae1.jpg?width=400&quality=80' },
  { id: 24, nameEn: 'Egg Mix Salad',                  nameAr: 'مكس بيض سلط',                         catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Salad',     sizeAr: 'سلطة',          price: 23, available: true, descEn: 'Boiled eggs, cheddar cheese, avocado and tomatoes with rocca salad and chips',    descAr: 'خلطة بيض مع جبن شيدر و افوكادو وطماطم مع سلطة روكا و شيبس',                  addEn: 'Extra Avocado, Extra Egg',           addAr: 'زيادة افوكادو، زيادة بيض',             img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/77100172?width=400&quality=80' },
  { id: 25, nameEn: 'Tuna Salad',                     nameAr: 'تونا سلط',                            catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Salad',     sizeAr: 'سلطة',          price: 24, available: true, descEn: 'Tuna or spicy tuna with avocado, pesto, tomato and rocca salad with chips',       descAr: 'تونا - افوكادو - بيستو - مع سلطة روكا و شيبس',                                addEn: 'Extra Tuna, Spicy',                  addAr: 'زيادة تونا، سبايسي',                   img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492902?width=400&quality=80' },
  { id: 26, nameEn: 'Chicken Salad',                  nameAr: 'تشيكن سلط',                           catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Salad',     sizeAr: 'سلطة',          price: 26, available: true, descEn: 'Grilled chicken salad, arugula, tomato and pesto with rocca salad and chips',     descAr: 'دجاج مشوي - جرجير - طماطم - بيستو مع سلطة روكا و شيبس',                      addEn: 'Extra Chicken, Extra Pesto',         addAr: 'زيادة دجاج، زيادة بيستو',              img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492917?width=400&quality=80' },
  { id: 27, nameEn: 'Cheesy Turkey Salad',            nameAr: 'تشيزي تيركي سلط',                    catEn: 'Ciabatta & Salad',     catAr: 'شيباتا و سلط',        sizeEn: 'Salad',     sizeAr: 'سلطة',          price: 25, available: true, descEn: 'Turkey slices, cheddar, mozzarella, pesto with rocca salad and chips',            descAr: 'شرائح تركي - جبن شيدر - جبن موزريلا - بيستو مع سلطة روكا و شيبس',            addEn: 'Extra Turkey, Extra Cheese',         addAr: 'زيادة تيركي، زيادة جبن',               img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492896?width=400&quality=80' },
  { id: 28, nameEn: 'Egg Sandwich',                   nameAr: 'ساندوتش بيض',                         catEn: 'Eggs And Kebda',       catAr: 'بيض و كبدة',          sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 5,  available: true, descEn: 'Egg sandwich with optional add-ons',                                              descAr: 'بيض مع امكانية اضافة جبن و شطة',                                               addEn: 'Extra Cheese, Extra Hot Sauce',      addAr: 'زيادة جبن، زيادة شطة',                 img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492959?width=400&quality=80' },
  { id: 29, nameEn: 'Cheesy Egg Sandwich',            nameAr: 'ساندوتش تشيزي بيض',                  catEn: 'Eggs And Kebda',       catAr: 'بيض و كبدة',          sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 7,  available: true, descEn: 'Egg with creamy cheese and yellow cheddar',                                       descAr: 'بيض مع جبن سائل و جبن شيدر اصفر',                                              addEn: 'Extra Cheese, Extra Hot Sauce',      addAr: 'زيادة جبن، زيادة شطة',                 img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492950?width=400&quality=80' },
  { id: 30, nameEn: 'Shakshuka Sandwich',             nameAr: 'ساندوتش شكشوكة',                      catEn: 'Eggs And Kebda',       catAr: 'بيض و كبدة',          sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 5,  available: true, descEn: 'Shakshuka with special recipe',                                                   descAr: 'شكشوكة بالخلطة الخاصة',                                                        addEn: 'Extra Cheese, Extra Hot Sauce',      addAr: 'زيادة جبن، زيادة شطة',                 img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492960?width=400&quality=80' },
  { id: 31, nameEn: 'Liver Sandwich',                 nameAr: 'ساندوتش كبدة',                        catEn: 'Eggs And Kebda',       catAr: 'بيض و كبدة',          sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 7,  available: true, descEn: 'Lamb liver served on samoli bread',                                               descAr: 'كبدة غنم سادة مع امكانية اضافة خيارات',                                        addEn: 'Extra Cheese, Extra Hot Sauce',      addAr: 'زيادة جبن، زيادة شطة',                 img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492963?width=400&quality=80' },
  { id: 32, nameEn: 'Liver Pie',                      nameAr: 'فطيرة كبده',                          catEn: 'Pies',                 catAr: 'الفطائر',              sizeEn: 'Pie',       sizeAr: 'فطيرة',         price: 10, available: true, descEn: 'Oven-baked lamb liver pie',                                                       descAr: 'فطيرة كبدة غنم في الفرن',                                                      addEn: 'Extra Cheese, Extra Hot Sauce',      addAr: 'زيادة جبن، زيادة شطة',                 img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/7e56887fc3555cea66c47c852ac16707.jpg?width=400&quality=80' },
  { id: 33, nameEn: 'Mix Cheese Pie',                 nameAr: 'فطيرة مكس أجبان',                     catEn: 'Pies',                 catAr: 'الفطائر',              sizeEn: 'Pie',       sizeAr: 'فطيرة',         price: 11, available: true, descEn: 'Mix of akawi and mozzarella cheese',                                              descAr: 'مكس اجبان مابين جبن عكاوي وجبن موزريلا',                                       addEn: 'Extra Cheese',                       addAr: 'زيادة جبن',                            img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492982?width=400&quality=80' },
  { id: 34, nameEn: 'Egg Pie',                        nameAr: 'فطيرة بيض',                           catEn: 'Pies',                 catAr: 'الفطائر',              sizeEn: 'Pie',       sizeAr: 'فطيرة',         price: 10, available: true, descEn: 'Oven-baked scrambled egg with special egg mix',                                   descAr: 'بيض سكرامبلد يُعد في الفرن بخلطة البيض الخاصة',                                addEn: 'Extra Cheese, Extra Hot Sauce',      addAr: 'زيادة جبن، زيادة شطة',                 img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/96bacc198157e89b87af49fe74d1b447.jpeg?width=400&quality=80' },
  { id: 35, nameEn: 'Halloumi Pie',                   nameAr: 'فطيرة حلومي',                         catEn: 'Pies',                 catAr: 'الفطائر',              sizeEn: 'Pie',       sizeAr: 'فطيرة',         price: 12, available: true, descEn: 'Halloumi, labneh, sun-dried tomato, olives, pesto',                               descAr: 'حلومي - خلطة لبنه - طماطم مجفف - زيتون - بيستو',                              addEn: 'Hot Sauce, Extra Dried Tomato, Extra Halloumi', addAr: 'زيادة شطة، طماطم مجففة، حلومي', img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492977?width=400&quality=80' },
  { id: 36, nameEn: 'Chicken Mozzarella Pie',         nameAr: 'فطيرة تشكين موزريلا',                 catEn: 'Pies',                 catAr: 'الفطائر',              sizeEn: 'Pie',       sizeAr: 'فطيرة',         price: 14, available: true, descEn: 'Chicken with mozzarella and special sauce',                                       descAr: 'دجاج مع جبن الموزريلا والصلصة الخاصة',                                         addEn: 'Extra Chicken, Extra Mozzarella',    addAr: 'زيادة دجاج، زيادة موزاريلا',           img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492974?width=400&quality=80' },
  { id: 37, nameEn: 'Chicken Pesto Pie',              nameAr: 'فطيرة تشكين بيستو',                   catEn: 'Pies',                 catAr: 'الفطائر',              sizeEn: 'Pie',       sizeAr: 'فطيرة',         price: 14, available: true, descEn: 'Chicken pie with pesto, chipotle, sun-dried tomato and mozzarella',               descAr: 'فطيرة الدجاج مع بيستو والصوص شيبوتلي والطماطم المجففه والجبن الموزريلا',       addEn: 'Extra Cheese, Extra Pesto, Sauce',   addAr: 'زيادة جبن، زيادة بيستو، صوص',         img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492975?width=400&quality=80' },
  { id: 38, nameEn: "Za'atar Pie",                    nameAr: 'فطيرة زعتر',                          catEn: 'Pies',                 catAr: 'الفطائر',              sizeEn: 'Pie',       sizeAr: 'فطيرة',         price: 8,  available: true, descEn: "Za'atar pie — add mozzarella or akawi",                                           descAr: 'زعتر مع امكانية اضافة جبن موزريلا أو عكاوي',                                   addEn: "Extra Za'atar, Extra Mozzarella",    addAr: 'زيادة زعتر، زيادة موزاريلا',           img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492985?width=400&quality=80' },
  { id: 39, nameEn: 'Labna Pie',                      nameAr: 'فطيرة لبنة',                          catEn: 'Pies',                 catAr: 'الفطائر',              sizeEn: 'Pie',       sizeAr: 'فطيرة',         price: 8,  available: true, descEn: 'Labneh pie — add za\'atar or honey',                                              descAr: 'فطيرة لبنة مع امكانية اضافة زعتر و عسل',                                       addEn: 'Extra Labneh',                       addAr: 'زيادة لبنة',                           img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/65492979?width=400&quality=80' },
  { id: 40, nameEn: 'Chicken Strips',                 nameAr: 'أصابع دجاج',                          catEn: 'Side Orders',          catAr: 'الطلبات الجانبية',     sizeEn: 'Cup',       sizeAr: 'كوب',           price: 14, available: true, descEn: '3 or 5 fried chicken strips with maple or truffle sauce',                        descAr: 'ثلاث أو خمس قطع أصابع دجاج مقلية مع صوص ميبل او ترافيل جانبي',               addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/06b835a23287548798c14f2cd7df1c52.jpeg?width=400&quality=80' },
  { id: 41, nameEn: 'Fries Sandwich',                 nameAr: 'ساندوتش بطاطس',                       catEn: 'Side Orders',          catAr: 'الطلبات الجانبية',     sizeEn: 'Sandwich',  sizeAr: 'ساندوتش',       price: 7,  available: true, descEn: 'Spiced fries with ketchup and mayonnaise',                                        descAr: 'بطاطس مبهر مع كاتشاب و مايونيز',                                               addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/91013/PRODUCT/65492997/860ed3c6-867b-4164-80e9-538f5e2f1708.jpg?width=400&quality=80' },
  { id: 42, nameEn: 'Chips',                          nameAr: 'شيبس',                                catEn: 'Side Orders',          catAr: 'الطلبات الجانبية',     sizeEn: 'Cup',       sizeAr: 'كوب',           price: 6,  available: true, descEn: 'Chips with house spices',                                                         descAr: 'شيبس مع بهارات البيت',                                                         addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/84911/PRODUCT/81889801/0db2b35c-0571-4c50-b09c-f8e014b1ec5b.jpg?width=400&quality=80' },
  { id: 43, nameEn: 'Tasali Fries',                   nameAr: 'بطاطس تسالي',                         catEn: 'Side Orders',          catAr: 'الطلبات الجانبية',     sizeEn: 'Cup',       sizeAr: 'كوب',           price: 8,  available: true, descEn: 'Spiced fries with ketchup, mayonnaise and creamy cheese',                         descAr: 'بطاطس مبهر مع كاتشب و مايونيز و جبن سائل',                                    addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/84911/PRODUCT/98246773/612942df-d690-4fc4-97a8-ddf7e06e3b61.jpg?width=400&quality=80' },
  { id: 44, nameEn: 'Fries',                          nameAr: 'بطاطس',                               catEn: 'Side Orders',          catAr: 'الطلبات الجانبية',     sizeEn: 'Cup',       sizeAr: 'كوب',           price: 7,  available: true, descEn: 'Fries served on a plate with side sauce',                                        descAr: 'بطاطس يقدم على طبق مع صوص جانبي',                                              addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/84911/PRODUCT/65492990/0e22b0f1-c034-4d3d-8345-78a907ce7a5f.jpg?width=400&quality=80' },
  { id: 45, nameEn: 'Mix Fries',                      nameAr: 'بطاطس لغاويص',                        catEn: 'Side Orders',          catAr: 'الطلبات الجانبية',     sizeEn: 'Cup',       sizeAr: 'كوب',           price: 11, available: true, descEn: 'Seasoned fries with Ghabashi sauce and crispy onion',                             descAr: 'بطاطس مبهر مع صوص غباشي والبصل المقرمش',                                       addEn: 'Extra Brisket, Extra Chicken',       addAr: 'زيادة بريسكت، زيادة دجاج',             img: 'https://images.deliveryhero.io/image/global-menu-service/HS_SA/vendor/84911/PRODUCT/65492995/cb5d5738-931e-4f7f-a0df-11ce6fc04830.jpg?width=400&quality=80' },
  { id: 46, nameEn: 'Ghabashi Sauce',                 nameAr: 'غباشي صوص',                           catEn: 'Side Orders',          catAr: 'الطلبات الجانبية',     sizeEn: 'Cup',       sizeAr: 'كوب',           price: 3,  available: true, descEn: 'Ghabashi special sauce',                                                          descAr: 'صوص غباشي الخاص',                                                              addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/e8979140378e03ba1458233e384daece.jpg?width=400&quality=80' },
  { id: 47, nameEn: 'Coca Cola',                      nameAr: 'كوكاكولا',                             catEn: 'Drinks',               catAr: 'المشروبات',             sizeEn: '355ml',     sizeAr: '٣٥٥مل',        price: 4,  available: true, descEn: '355ml cola',                                                                      descAr: 'كوكاكولا ٣٥٥مل',                                                               addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/b9f3978b0d85ab1f5b39d0c82d705423.jpg?width=400&quality=80' },
  { id: 48, nameEn: 'Coca Cola Light',                nameAr: 'كوكاكولا لايت',                       catEn: 'Drinks',               catAr: 'المشروبات',             sizeEn: '355ml',     sizeAr: '٣٥٥مل',        price: 4,  available: true, descEn: '355ml diet cola',                                                                 descAr: 'كوكاكولا لايت ٣٥٥مل',                                                          addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/29c140c30238bbb58f4454205781fed7.jpg?width=400&quality=80' },
  { id: 49, nameEn: 'Sprite',                         nameAr: 'سبرايت',                              catEn: 'Drinks',               catAr: 'المشروبات',             sizeEn: '355ml',     sizeAr: '٣٥٥مل',        price: 4,  available: true, descEn: '355ml lemon-lime soft drink',                                                     descAr: 'سبرايت ٣٥٥ مل',                                                                addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/6863ab4835324ae65443647485c715e5.jpg?width=400&quality=80' },
  { id: 50, nameEn: 'Al Rabie Orange Juice',          nameAr: 'عصير ربيع برتقال',                    catEn: 'Drinks',               catAr: 'المشروبات',             sizeEn: 'Pack',      sizeAr: 'علبة',          price: 3,  available: true, descEn: 'Packaged orange juice',                                                           descAr: 'عصير ربيع برتقال',                                                              addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/hungerstation/menuitem/image/7fcaeab727d1f7823d18e8a1dcc0af7f?width=400&quality=80' },
  { id: 51, nameEn: 'Orange Juice',                   nameAr: 'عصير برتقال طبيعي',                   catEn: 'Drinks',               catAr: 'المشروبات',             sizeEn: 'Cup',       sizeAr: 'كوب',           price: 9,  available: true, descEn: 'Fresh orange juice',                                                              descAr: 'عصير برتقال طازج طبيعي',                                                       addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/5dd4d6f20209f0287cc14b278983e6fa.jpg?width=400&quality=80' },
  { id: 52, nameEn: 'Pink Lemonade',                  nameAr: 'عصير بينك لومنيد طبيعي',              catEn: 'Drinks',               catAr: 'المشروبات',             sizeEn: 'Cup',       sizeAr: 'كوب',           price: 9,  available: true, descEn: 'Natural pink lemonade',                                                           descAr: 'بينك ليموناد طبيعي',                                                           addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/8769b70dad8833a2bdb93796ad9bb7f6.jpg?width=400&quality=80' },
  { id: 53, nameEn: 'Water',                          nameAr: 'ماء',                                  catEn: 'Drinks',               catAr: 'المشروبات',             sizeEn: 'Bottle',    sizeAr: 'زجاجة',         price: 1,  available: true, descEn: 'Bottled water',                                                                   descAr: 'مياه معبأة',                                                                   addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/0774033967dad584f5567747541638bb.jpg?width=400&quality=80' },
  { id: 54, nameEn: 'Karak',                          nameAr: 'كرك',                                  catEn: 'Drinks',               catAr: 'المشروبات',             sizeEn: '12oz Cup',  sizeAr: 'كوب ١٢ اونص',  price: 6,  available: true, descEn: 'Karak tea with special blend, 12oz cup',                                          descAr: 'كرك بخلطة خاصة بكوب ١٢ اونص',                                                 addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/312844dbe380d101fc2121cf1b966568.jpg?width=400&quality=80' },
  { id: 55, nameEn: 'Tea',                            nameAr: 'شاهي',                                 catEn: 'Drinks',               catAr: 'المشروبات',             sizeEn: '12oz Cup',  sizeAr: 'كوب ١٢ اونص',  price: 4,  available: true, descEn: 'Tea with special blend, 12oz cup',                                                descAr: 'شاهي بخلطة خاصة بكوب ١٢ اونص',                                                addEn: '', addAr: '', img: 'https://images.deliveryhero.io/image/menu-import-gateway-prd/regions/ME/chains/HS-GBAS/1423c52761b0382473f59e5ce95d0862.png?width=400&quality=80' },
]
