export const SEED_CATEGORIES = [
  { id: 1, name_en: 'Rice Plates', name_ar: 'أطباق الأرز', sort_order: 1 },
  { id: 2, name_en: 'Salads', name_ar: 'السلطات', sort_order: 2 },
  { id: 3, name_en: 'Sandwiches', name_ar: 'الساندويشات', sort_order: 3 },
  { id: 4, name_en: 'Chips', name_ar: 'الشبس', sort_order: 4 },
  { id: 5, name_en: 'Granola & Yogurt', name_ar: 'جرانولا وزبادي', sort_order: 5 },
  { id: 6, name_en: 'Dips', name_ar: 'التغميسات', sort_order: 6 },
  { id: 7, name_en: 'Crunches', name_ar: 'المقرمشات', sort_order: 7 },
  { id: 8, name_en: 'Healthy Sweets', name_ar: 'الحلويات الصحية', sort_order: 8 },
  { id: 9, name_en: 'Sauces', name_ar: 'الصوصات', sort_order: 9 },
  { id: 10, name_en: 'Beverages', name_ar: 'المشروبات', sort_order: 10 },
  { id: 11, name_en: 'Pickles', name_ar: 'المخللات', sort_order: 11 },
]

export const SEED_MENU_ITEMS = [
  { id: 100, name_en: 'Ground Beef with Brown Rice', name_ar: 'لحم مفروم مع رز بني', price: 29, calories: 455, category: 'Rice Plates', is_available: true, sort_order: 1 },
  { id: 72, name_en: 'Chicken Rice', name_ar: 'دجاج مع رز', price: 28, calories: 394, category: 'Rice Plates', is_available: true, sort_order: 2 },
  { id: 74, name_en: 'Salmon Rice', name_ar: 'سالمون مع رز', price: 34, calories: 437, category: 'Rice Plates', is_available: true, sort_order: 3 },
  { id: 10, name_en: 'Chicken Crunch Salad', name_ar: 'سلطة تشيكن كرانش', price: 27, calories: 244, category: 'Salads', is_available: true, sort_order: 4 },
  { id: 9, name_en: 'Avocado Salad', name_ar: 'سلطة الافوكادو', price: 27, calories: 304, category: 'Salads', is_available: true, sort_order: 5 },
  { id: 4, name_en: 'Crisp Salad', name_ar: 'سلطة كريسب', price: 27, calories: 380, category: 'Salads', is_available: true, sort_order: 6 },
  { id: 11, name_en: 'Shrimp Salad', name_ar: 'سلطة الروبيان', price: 28, calories: 276.5, category: 'Salads', is_available: true, sort_order: 7 },
  { id: 8, name_en: 'Crab Salad', name_ar: 'سلطة كراب', price: 28, calories: 180, category: 'Salads', is_available: true, sort_order: 8 },
  { id: 3, name_en: 'Lentil Salad', name_ar: 'سلطة العدس', price: 21, calories: 347, category: 'Salads', is_available: true, sort_order: 9 },
  { id: 5, name_en: 'Mexican Salad', name_ar: 'سلطة مكسيكية', price: 27, calories: 304, category: 'Salads', is_available: true, sort_order: 10 },
  { id: 15, name_en: 'Grilled Chicken', name_ar: 'ساندوتش الدجاج المشوي', price: 18, calories: 295, category: 'Sandwiches', is_available: true, sort_order: 11 },
  { id: 14, name_en: 'Spicy Grilled Chicken', name_ar: 'سبايسي الدجاج المشوي', price: 18, calories: 300, category: 'Sandwiches', is_available: true, sort_order: 12 },
  { id: 103, name_en: 'Pesto Chicken Grill Sandwich', name_ar: 'ساندويتش بيستو دجاج مشوي', price: 20, calories: 485, category: 'Sandwiches', is_available: true, sort_order: 13 },
  { id: 18, name_en: 'Tuna Sandwich', name_ar: 'تونا ساندوتش', price: 18, calories: 375, category: 'Sandwiches', is_available: true, sort_order: 14 },
  { id: 102, name_en: 'Egg Salad Sandwich', name_ar: 'ساندويتش سلطة بيض', price: 14, calories: 580, category: 'Sandwiches', is_available: true, sort_order: 15 },
  { id: 101, name_en: 'Burrata Sandwich', name_ar: 'بوراتا ساندويتش', price: 17, calories: 454, category: 'Sandwiches', is_available: true, sort_order: 16 },
  { id: 22, name_en: 'Cheesy Turkey', name_ar: 'ساندوتش تركي', price: 18, calories: 508, category: 'Sandwiches', is_available: true, sort_order: 17 },
  { id: 21, name_en: 'Halloumi Sandwich', name_ar: 'ساندوتش حلومي', price: 17, calories: 464, category: 'Sandwiches', is_available: true, sort_order: 18 },
  { id: 19, name_en: 'PB & Strawberry Jam', name_ar: 'فول سوداني مربى فراولة', price: 12, calories: 537, category: 'Sandwiches', is_available: true, sort_order: 19 },
  { id: 20, name_en: 'PB & Blueberry Jam', name_ar: 'فول سوداني مربى بلو بيري', price: 13, calories: 540, category: 'Sandwiches', is_available: true, sort_order: 20 },
  { id: 16, name_en: 'Spicy Tuna', name_ar: 'سبايسي تونا', price: 18, calories: 375, category: 'Sandwiches', is_available: true, sort_order: 21 },
  { id: 23, name_en: 'Sweet Potato Chips', name_ar: 'رقائق البطاطس الحلوة', price: 8, calories: 23, category: 'Chips', is_available: true, sort_order: 22 },
  { id: 25, name_en: 'Beetroot Chips', name_ar: 'رقائق الشمندر', price: 8, calories: 32, category: 'Chips', is_available: false, sort_order: 23 },
  { id: 24, name_en: 'Mix Chips', name_ar: 'مكس شبس', price: 9, calories: 28, category: 'Chips', is_available: false, sort_order: 24 },
  { id: 30, name_en: 'Strawberry Yogurt Granola', name_ar: 'زبادي جرانولا مع الفراولة', price: 12, calories: 479, category: 'Granola & Yogurt', is_available: true, sort_order: 25 },
  { id: 29, name_en: 'Blueberry Yogurt Granola', name_ar: 'زبادي جرانولا مع بلوبيري', price: 12, calories: 561, category: 'Granola & Yogurt', is_available: true, sort_order: 26 },
  { id: 27, name_en: 'Granola', name_ar: 'جرانولا', price: 14, calories: 340, category: 'Granola & Yogurt', is_available: true, sort_order: 27 },
  { id: 28, name_en: 'Chocolate Granola', name_ar: 'جرانولا الشوكولاتة', price: 14, calories: 350, category: 'Granola & Yogurt', is_available: true, sort_order: 28 },
  { id: 37, name_en: 'Hummus', name_ar: 'الحمص', price: 10, calories: 454, category: 'Dips', is_available: false, sort_order: 29 },
  { id: 36, name_en: 'Hummus Avocado', name_ar: 'حمص افوكادو', price: 13, calories: 442, category: 'Dips', is_available: false, sort_order: 30 },
  { id: 35, name_en: 'Beetroot Hummus', name_ar: 'حمص شمندر', price: 13, calories: 490, category: 'Dips', is_available: false, sort_order: 31 },
  { id: 33, name_en: 'Labneh Dip', name_ar: 'تغميسة لبنة', price: 12, calories: 608, category: 'Dips', is_available: false, sort_order: 32 },
  { id: 34, name_en: 'Jalapeno Dip', name_ar: 'تغميسة هالبينو', price: 12, calories: 608, category: 'Dips', is_available: false, sort_order: 33 },
  { id: 31, name_en: 'Guacamole Dip', name_ar: 'تغميسة جواكامولي', price: 10, calories: 608, category: 'Dips', is_available: false, sort_order: 34 },
  { id: 42, name_en: 'Protein Crackers', name_ar: 'مقرمشات بروتين', price: 11, calories: 194, category: 'Crunches', is_available: true, sort_order: 35 },
  { id: 43, name_en: "Za'atar Crackers", name_ar: 'مقرمشات زعتر', price: 7, calories: 230, category: 'Crunches', is_available: true, sort_order: 36 },
  { id: 44, name_en: "Za'atar Chocolate Crackers", name_ar: 'مقرمشات زعتر شوكولاتة', price: 9, calories: 240, category: 'Crunches', is_available: true, sort_order: 37 },
  { id: 48, name_en: 'Crunchy Corn', name_ar: 'ذرة مقرمشة', price: 7, calories: 250, category: 'Crunches', is_available: true, sort_order: 38 },
  { id: 45, name_en: 'Chocolate Biscuit', name_ar: 'بسكويت شوكولاتة', price: 9, calories: 280, category: 'Crunches', is_available: true, sort_order: 39 },
  { id: 104, name_en: 'Chocolate Protein Sticks', name_ar: 'عيدان بروتين شوكولاتة', price: 13, calories: 250, category: 'Crunches', is_available: true, sort_order: 40 },
  { id: 47, name_en: 'Rusk Finger Chocolate', name_ar: 'أصابع شابورة شوكولاتة', price: 9, calories: 300, category: 'Crunches', is_available: false, sort_order: 41 },
  { id: 46, name_en: 'Cake Rusk', name_ar: 'شابورة كيك', price: 9, calories: 482, category: 'Crunches', is_available: false, sort_order: 42 },
  { id: 99, name_en: 'Overnight Tiramisu', name_ar: 'تيراميسو أوفرنايت', price: 16, calories: 225, category: 'Healthy Sweets', is_available: true, sort_order: 43 },
  { id: 105, name_en: 'Chocolate Pudding', name_ar: 'شوكولاتة بودينق', price: 15, calories: 290, category: 'Healthy Sweets', is_available: true, sort_order: 44 },
  { id: 106, name_en: 'Chocolate Pudding With Peanut Butter', name_ar: 'شوكولاتة بودينق مع فول سوادني', price: 17, calories: 390, category: 'Healthy Sweets', is_available: true, sort_order: 45 },
  { id: 52, name_en: 'Healthy Snickers Cake', name_ar: 'كيكة سنيكرز الصحية', price: 11, calories: 317, category: 'Healthy Sweets', is_available: true, sort_order: 46 },
  { id: 55, name_en: 'Protein Butter Bar', name_ar: 'بروتين بار بتر', price: 7, calories: 280, category: 'Healthy Sweets', is_available: true, sort_order: 47 },
  { id: 53, name_en: 'Protein Crunchy Rice', name_ar: 'كرنشي رايز بروتين بار', price: 8, calories: 194, category: 'Healthy Sweets', is_available: true, sort_order: 48 },
  { id: 107, name_en: 'Dark Protein Rocky Road', name_ar: 'دارك بروتين روكي رود', price: 12, calories: 300, category: 'Healthy Sweets', is_available: true, sort_order: 49 },
  { id: 108, name_en: 'Dark Chocolate Protein Bar', name_ar: 'دارك شوكولاتة بروتين بار', price: 9, calories: 190, category: 'Healthy Sweets', is_available: true, sort_order: 50 },
  { id: 109, name_en: 'Brownie Balls', name_ar: 'براونيز', price: 14, calories: 200, category: 'Healthy Sweets', is_available: true, sort_order: 51 },
  { id: 51, name_en: 'Jam Strawberry', name_ar: 'مربى فراولة', price: 14, calories: 195, category: 'Healthy Sweets', is_available: false, sort_order: 52 },
  { id: 50, name_en: 'Jam Blueberry', name_ar: 'مربى بلوبيري', price: 14, calories: 195, category: 'Healthy Sweets', is_available: false, sort_order: 53 },
  { id: 49, name_en: 'Jam Fig', name_ar: 'مربى تين', price: 14, calories: 186, category: 'Healthy Sweets', is_available: false, sort_order: 54 },
  { id: 54, name_en: 'Coconut Protein Bar', name_ar: 'بروتين جوز الهند', price: 9, calories: 231, category: 'Healthy Sweets', is_available: false, sort_order: 55 },
  { id: 56, name_en: 'Caesar Sauce', name_ar: 'سيزر صوص', price: 4, calories: 290, category: 'Sauces', is_available: true, sort_order: 56 },
  { id: 58, name_en: 'Avo Sauce', name_ar: 'افو صوص', price: 4, calories: 192, category: 'Sauces', is_available: true, sort_order: 57 },
  { id: 59, name_en: 'Crab Sauce', name_ar: 'كراب صوص', price: 4, calories: 100, category: 'Sauces', is_available: false, sort_order: 58 },
  { id: 60, name_en: 'Asian Sauce', name_ar: 'صوص اسيوي', price: 4, calories: 230, category: 'Sauces', is_available: true, sort_order: 59 },
  { id: 57, name_en: 'Green Sauce', name_ar: 'قرين صوص', price: 4, calories: 278, category: 'Sauces', is_available: true, sort_order: 60 },
  { id: 61, name_en: 'Viney Sauce', name_ar: 'فيني صوص', price: 4, calories: 182, category: 'Sauces', is_available: true, sort_order: 61 },
  { id: 63, name_en: 'Fresh Green Juice', name_ar: 'عصير اخضر طبيعي', price: 10, calories: 123, category: 'Beverages', is_available: true, sort_order: 62 },
  { id: 64, name_en: 'Beetroot Juice', name_ar: 'عصير شمندر', price: 10, calories: 138, category: 'Beverages', is_available: true, sort_order: 63 },
  { id: 65, name_en: 'Fresh Orange Juice', name_ar: 'عصير برتقال طبيعي', price: 11, calories: 163, category: 'Beverages', is_available: true, sort_order: 64 },
  { id: 66, name_en: 'Protein Avocado Smoothie', name_ar: 'سموذي بروتين افوكادو', price: 13, calories: 399, category: 'Beverages', is_available: true, sort_order: 65 },
  { id: 67, name_en: 'Protein Dates Smoothie', name_ar: 'سموذي بروتين التمر', price: 13, calories: 416, category: 'Beverages', is_available: true, sort_order: 66 },
  { id: 68, name_en: 'Coca Cola Zero', name_ar: 'كوكاكولا زيرو', price: 4, calories: 60, category: 'Beverages', is_available: true, sort_order: 67 },
  { id: 69, name_en: 'Coca Cola Light', name_ar: 'كوكاكولا لايت', price: 4, calories: 60, category: 'Beverages', is_available: true, sort_order: 68 },
  { id: 70, name_en: 'Perrier Sparkling Water', name_ar: 'بيريه ماء غازية', price: 6, calories: 1, category: 'Beverages', is_available: true, sort_order: 69 },
  { id: 62, name_en: 'Ginger Lemon', name_ar: 'زنجبيل ليمون', price: 10, calories: 123, category: 'Beverages', is_available: false, sort_order: 70 },
  { id: 71, name_en: 'Still Water', name_ar: 'ماء معدنية', price: 1, calories: 1, category: 'Beverages', is_available: true, sort_order: 71 },
  { id: 38, name_en: 'Halloumi Olives Plate', name_ar: 'طبق حلومي و زيتون', price: 15, calories: 325, category: 'Pickles', is_available: false, sort_order: 72 },
  { id: 39, name_en: 'Small Cucumber Pickle', name_ar: 'مخلل الخيار الصغير', price: 8, calories: 10, category: 'Pickles', is_available: false, sort_order: 73 },
  { id: 40, name_en: 'Mix Pickles', name_ar: 'مخلل منوع', price: 8, calories: 12, category: 'Pickles', is_available: false, sort_order: 74 },
  { id: 41, name_en: 'Pepper Pickles', name_ar: 'مخلل فلفل', price: 8, calories: 22, category: 'Pickles', is_available: false, sort_order: 75 },
]

export const SEED_EMPLOYEES = [
  { id: 1, name: 'Asjad Puthuparambil Ayoob', iqama: '2512263506', iban: 'SA4405000068204791913000', basic_salary: 1800, ot_hours: 0, position: 'Operation Manager', branch: 'Ar Rayyan', shift: 'Morning', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 2, name: 'Abdul Sattar', iqama: '2547796033', iban: 'SA6080000331608016563777', basic_salary: 3000, ot_hours: 0, position: 'Manager', branch: 'Hittin', shift: 'Morning', salary_paid: false, vacation_status: 'none', restaurant: 'Appetie' },
  { id: 3, name: 'Mohammed Arman Uddin', iqama: '2499854418', iban: 'SA4505000068204453945000', basic_salary: 1600, ot_hours: 39.96, position: 'Pie / Cashier', branch: 'Ar Rayyan', shift: 'Night', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 4, name: 'Mohin Uddin RONY', iqama: '2533087983', iban: 'SA3430100942000145005306', basic_salary: 1600, ot_hours: 25.97, position: 'Pie / Grill / Cashier', branch: 'Malqa', shift: 'Night', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 5, name: 'Shanavas Aliyarukunju', iqama: '2512279700', iban: 'SA5305000068204840815000', basic_salary: 1600, ot_hours: 39.96, position: 'Grill', branch: 'Ar Rayyan', shift: 'Night', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 6, name: 'Razwan Sulaiman', iqama: '2548287891', iban: 'SA2430100942000163761309', basic_salary: 1500, ot_hours: 48, position: 'Cashier / Salad / Prep', branch: 'Ar Rayyan', shift: 'Double Shift', salary_paid: false, vacation_status: 'none', restaurant: 'Appetie' },
  { id: 7, name: 'Yeasin Hossain', iqama: '2540739717', iban: 'SA8880000996608016448058', basic_salary: 2000, ot_hours: 25, position: 'Pie / Grill / Cashier', branch: 'Malqa', shift: 'Morning', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 8, name: 'MD Abdullah Mia', iqama: '2513753190', iban: 'SA8480000355608018485558', basic_salary: 1500, ot_hours: 26.64, position: 'Pie', branch: 'Malqa', shift: 'Morning', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 9, name: 'Mohammad Hasnain Nizamuddin Pathan', iqama: '2540243629', iban: 'SA3780000640608018938239', basic_salary: 1500, ot_hours: 0, position: 'Preparation', branch: 'Ar Rayyan', shift: 'Morning', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 10, name: 'Opendra Giri', iqama: '2513564753', iban: 'SA7180000609608016080199', basic_salary: 1700, ot_hours: 25, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 11, name: 'MD Zakaria Saleh Ahmed', iqama: '2510824879', iban: 'SA2810000011100291917500', basic_salary: 1500, ot_hours: 48, position: 'Cashier / Salad / Prep', branch: 'Ar Rayyan', shift: 'Night', salary_paid: false, vacation_status: 'none', restaurant: 'Appetie' },
  { id: 12, name: 'Muhammad Amjad Sulaiman', iqama: '2531090419', iban: 'SA1930100942000151942628', basic_salary: 1600, ot_hours: 67.5, position: 'Pie / Grill / Cashier', branch: 'Hittin', shift: 'Morning', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 13, name: 'Jahid Hossen Joni', iqama: '2496241569', iban: '', basic_salary: 2500, ot_hours: 7, position: 'Bakery Chef', branch: 'Hittin', shift: 'Evening', salary_paid: false, vacation_status: 'none', restaurant: 'Bakery' },
  { id: 14, name: 'Shahidul Islam', iqama: '2538972593', iban: 'SA0380000640608018181087', basic_salary: 1600, ot_hours: 24.9, position: 'Pie / Grill / Cashier', branch: 'Hittin', shift: 'Night', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 15, name: 'Tipusulthan Nizamuddin Pathan', iqama: '2547796561', iban: 'SA4830100942000163458043', basic_salary: 1500, ot_hours: 26.64, position: 'Grill', branch: 'Hittin', shift: 'Double Shift', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 16, name: 'MD Monoar Hossain', iqama: '2531395412', iban: 'SA8580000640608016822872', basic_salary: 1500, ot_hours: 26.64, position: 'Pie', branch: 'Hittin', shift: 'Night', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 17, name: 'Kawsar Hossain', iqama: '2554728341', iban: 'SA3330100942000173841969', basic_salary: 1500, ot_hours: 75, position: 'Cashier / Salad / Prep', branch: 'Ar Rayyan', shift: 'Double Shift', salary_paid: false, vacation_status: 'none', restaurant: 'Appetie' },
  { id: 18, name: 'Shanto', iqama: '2558857922', iban: 'BY CASH', basic_salary: 2100, ot_hours: 31.97, position: 'Cashier / Salad / Prep', branch: 'Hittin', shift: 'Double Shift', salary_paid: false, vacation_status: 'none', restaurant: 'Appetie' },
  { id: 19, name: 'Ansar Mohammed Mutam', iqama: '2530995782', iban: 'BY CASH', basic_salary: 2500, ot_hours: 0, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 20, name: 'Harshith Janardhana', iqama: '2562898698', iban: 'BY CASH', basic_salary: 1500, ot_hours: 26.64, position: '', branch: 'Malqa', shift: 'Double Shift', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 21, name: 'Sunaif Hyder', iqama: '2562589321', iban: 'BY CASH', basic_salary: 1500, ot_hours: 27, position: 'Bakery Chef', branch: 'Hittin', shift: 'Evening', salary_paid: false, vacation_status: 'none', restaurant: 'Bakery' },
  { id: 22, name: 'Roopith Kumar-Kaniyoor', iqama: '2580639652', iban: 'BY CASH', basic_salary: 1500, ot_hours: 0, position: 'Cashier / Salad / Prep', branch: 'Hittin', shift: 'Night', salary_paid: false, vacation_status: 'none', restaurant: 'Appetie' },
  { id: 23, name: 'Niyas', iqama: '2610944007', iban: 'BY CASH', basic_salary: 2100, ot_hours: 0, position: 'Salad / Preparation', branch: 'Hittin', shift: 'Night', salary_paid: false, vacation_status: 'none', restaurant: 'Appetie' },
  { id: 24, name: 'Irshad', iqama: '', iban: 'BY CASH', basic_salary: 2100, ot_hours: 40, position: 'Grill', branch: 'Malqa', shift: 'Night', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 25, name: 'Taha', iqama: '2543190991', iban: 'BY CASH', basic_salary: 3000, ot_hours: 0, position: 'Head Chef', branch: 'Hittin', shift: 'Morning', salary_paid: false, vacation_status: 'none', restaurant: 'Bakery' },
  { id: 26, name: 'Riyadh', iqama: '', iban: 'BY CASH', basic_salary: 2100, ot_hours: 34.23, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 27, name: 'Refad', iqama: '', iban: 'BY CASH', basic_salary: 2100, ot_hours: 25, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 28, name: 'Abdul Malik', iqama: '', iban: 'BY CASH', basic_salary: 2100, ot_hours: 25, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 29, name: 'Ashraf', iqama: '', iban: 'BY CASH', basic_salary: 2100, ot_hours: 25, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 30, name: 'Baizid', iqama: '', iban: 'BY CASH', basic_salary: 2100, ot_hours: 75.06, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 31, name: 'Shah Alam', iqama: '', iban: 'BY CASH', basic_salary: 2100, ot_hours: 25, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 32, name: 'Abu Sayed', iqama: '', iban: 'BY CASH', basic_salary: 2100, ot_hours: 9.52, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 33, name: 'Rifat Bhuiyan', iqama: '', iban: 'BY CASH', basic_salary: 2500, ot_hours: 7, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 34, name: 'Nazim', iqama: '', iban: 'BY CASH', basic_salary: 2500, ot_hours: 8, position: '', branch: '', shift: '', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 35, name: 'Sheik Mohammed Arif', iqama: '2540243959', iban: 'SA1405000068205780555000', basic_salary: 1500, ot_hours: 0, position: '', branch: 'Ar Rayyan', shift: 'Morning', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
  { id: 36, name: 'Aboobakkar Siddiq', iqama: '2548287602', iban: 'SA8630100942000163647382', basic_salary: 1500, ot_hours: 0, position: 'Pie', branch: 'Hittin', shift: 'Morning', salary_paid: false, vacation_status: 'none', restaurant: 'Ghabashi' },
]

export const SEED_BRANCHES = [
  { id: 1, name: 'Ar Rayyan', location: 'Ar Rayyan, Riyadh', is_active: true },
  { id: 2, name: 'Hittin', location: 'Hittin, Riyadh', is_active: true },
  { id: 3, name: 'Malqa', location: 'Al Malqa, Riyadh', is_active: true },
]
export const ITEM_DETAILS: Record<number, { descEn: string; descAr: string; size: string; nutrition: { fat: number; carbs: number; protein: number; sugars: number } | null; allergens: string[] }> = {
  3: { descEn: "Green lentil, lettuce, chickpeas, roasted sweet potato, tomato, spring onion, rocket, dill, crispy potato, pumpkin seed, lemon vinaigrette dressing.", descAr: "عدس أخضر، خس، حمص، بطاطا حلوة مشوية، طماطم، بصل أخضر، جرجير، شبت، بطاطا مقرمشة، بذور اليقطين، صوص خل الليمون الصحي.", size: "48 oz", nutrition: { fat: 13, carbs: 44, protein: 19, sugars: 7.2 }, allergens: ["gluten"] },
  4: { descEn: "Grilled chicken, baked okra, roasted sweet potato, corn, croutons, crispy onion, healthy dressing.", descAr: "خس، دجاج مشوي، حمص، خبز محمص، جبن بارميزان، شرائح لوز، صوص سيزر الصحي.", size: "48 oz", nutrition: { fat: 22.3, carbs: 53.9, protein: 46, sugars: 6.9 }, allergens: ["gluten", "dairy", "nuts"] },
  5: { descEn: "Grilled chicken, lettuce, pickled onion, red beans, corn, quinoa, tomato, pepper, Doritos, chipotle sauce.", descAr: "دجاج مشوي، خس، بصل مخلل، فاصوليا حمراء، ذرة حلوة، كينوا، طماطم، فلفل بارد، رقائق دوريتو، صوص شيبوتلي الصحي.", size: "48 oz", nutrition: { fat: 11.6, carbs: 33, protein: 25, sugars: 6.1 }, allergens: ["gluten", "dairy"] },
  8: { descEn: "Crab, cucumber, carrot, mango, red cabbage, green beans, crab dressing.", descAr: "كراب مبشور، خيار، جزر، مانجو، ملفوف أحمر، فاصوليا خضراء، كراب مقرمش، صوص الكراب.", size: "48 oz", nutrition: { fat: 2, carbs: 25, protein: 18, sugars: 13.7 }, allergens: ["soy", "shellfish"] },
  9: { descEn: "Cubed avocado, grilled chicken, lettuce, pickled onion, quinoa, cucumber, cherry tomato, Doritos, avocado dressing.", descAr: "أفوكادو مكعبات، دجاج مشوي، خس، بصل مخلل، كينوا، خيار، طماطم كرزية، رقائق دوريتو، صوص الأفوكادو.", size: "48 oz", nutrition: { fat: 17.6, carbs: 33, protein: 25, sugars: 5.04 }, allergens: ["gluten"] },
  10: { descEn: "Lettuce, grilled chicken, chickpea, croutons, parmesan, sliced almonds, caesar dressing.", descAr: "دجاج مشوي، بامية مقلية، بطاطا حلوة محمصة، ذرة حلوة، خبز محمص، بصل مقرمش، صوص كريسب الصحي.", size: "48 oz", nutrition: { fat: 4.9, carbs: 27, protein: 28, sugars: 6.4 }, allergens: ["gluten", "dairy", "nuts"] },
  11: { descEn: "Grilled shrimp, lettuce, arugula, shredded carrot, beetroot, dried tomato, quinoa, balsamic dressing.", descAr: "روبيان مشوي، خس، جرجير، جزر مبشور، شمندر مبشور، طماطم مجففة، كينوا، فاصوليا خضراء، شمندر مقرمش، صوص البلسمك.", size: "48 oz", nutrition: { fat: 3.5, carbs: 36, protein: 25, sugars: 20.5 }, allergens: ["soy", "shellfish"] },
  14: { descEn: "Sourdough, grilled chicken, jalapeño, tabasco, tomato, avocado, cheddar, chipotle sauce.", descAr: "دجاج مشوي، هالبينو، تباسكو، طماطم، أفوكادو، جبن مبشور، صوص شيبوتلي.", size: "Sandwich", nutrition: { fat: 13.5, carbs: 44, protein: 35, sugars: 1.6 }, allergens: ["dairy", "gluten"] },
  15: { descEn: "Sourdough bread, grilled chicken, tomato, avocado, cheddar cheese, chipotle sauce.", descAr: "دجاج مشوي، طماطم، أفوكادو، جبن مبشور، بيستو.", size: "Sandwich", nutrition: { fat: 13.5, carbs: 44, protein: 35, sugars: 1.6 }, allergens: ["dairy", "gluten"] },
  16: { descEn: "Sugar & fat-free sourdough, tuna mix, avocado, tomato, cheddar, pesto, jalapeño, tabasco.", descAr: "خلطة تونا صحية، أفوكادو، طماطم، جبن مبشور، بيستو، هالبينو، تباسكو.", size: "Sandwich", nutrition: { fat: 10.6, carbs: 34, protein: 29, sugars: 1.1 }, allergens: ["fish", "dairy", "gluten"] },
  18: { descEn: "Sourdough, healthy tuna mixture, avocado, tomato, cheddar, pesto.", descAr: "خلطة تونا صحية، أفوكادو، طماطم، جبن مبشور، بيستو.", size: "Sandwich", nutrition: { fat: 10.6, carbs: 34, protein: 29, sugars: 1.1 }, allergens: ["fish", "dairy", "gluten"] },
  19: { descEn: "Peanut butter with strawberry jam on sourdough.", descAr: "زبدة فول سوداني مع مربى فراولة على خبز طازج.", size: "Sandwich", nutrition: { fat: 28, carbs: 54, protein: 17, sugars: 12 }, allergens: ["peanuts", "gluten"] },
  20: { descEn: "Peanut butter with blueberry jam on sourdough.", descAr: "زبدة فول سوداني مع مربى بلوبيري على خبز طازج.", size: "Sandwich", nutrition: { fat: 28, carbs: 55, protein: 16, sugars: 13 }, allergens: ["peanuts", "gluten"] },
  21: { descEn: "Sourdough, smoked halloumi, dried tomato, olives, pesto, labneh sauce.", descAr: "حلومي مشوي، طماطم مجففة، زيتون، بيستو، صوص لبنة.", size: "Sandwich", nutrition: { fat: 19.7, carbs: 45, protein: 23, sugars: 1 }, allergens: ["dairy", "gluten"] },
  22: { descEn: "Sourdough, smoked turkey, cheddar cheese, avocado, pesto, arugula, turkey sauce.", descAr: "ديك رومي مدخن، جبن مبشور، أفوكادو، بيستو، جرجير، صوص التركي.", size: "Sandwich", nutrition: { fat: 15.1, carbs: 34, protein: 39, sugars: 1 }, allergens: ["dairy", "gluten"] },
  23: { descEn: "25g of sweet potato with sea salt.", descAr: "رقائق بطاطا حلوة مخبوزة — خفيفة ومقرمشة.", size: "6 oz", nutrition: { fat: 3, carbs: 4.9, protein: 1, sugars: 1 }, allergens: [] },
  24: { descEn: "A colourful mix of sweet potato and beetroot chips.", descAr: "مزيج ملون من رقائق البطاطا الحلوة والشمندر.", size: "6 oz", nutrition: { fat: 6, carbs: 3, protein: 1, sugars: 3 }, allergens: [] },
  25: { descEn: "Crispy baked beetroot chips — naturally sweet and crunchy.", descAr: "رقائق شمندر مخبوزة — حلوة طبيعياً ومقرمشة.", size: "6 oz", nutrition: { fat: 1, carbs: 2.4, protein: 1, sugars: 2 }, allergens: [] },
  27: { descEn: "Rolled oats with healthy nuts, seeds and honey.", descAr: "جرانولا كلاسيكية مقرمشة مع شوفان ومكونات طبيعية.", size: "12 oz", nutrition: { fat: 55, carbs: 60, protein: 6, sugars: 24 }, allergens: ["nuts", "gluten"] },
  28: { descEn: "Rolled oats with healthy nuts, seeds, and chocolate.", descAr: "جرانولا شوكولاتة غنية مع كاكاو وشوفان.", size: "12 oz", nutrition: { fat: 55, carbs: 55, protein: 7, sugars: 24 }, allergens: ["nuts", "gluten"] },
  29: { descEn: "Greek yogurt, chia, granola mix with blueberry.", descAr: "زبادي يوناني مع جرانولا مقرمشة وبلوبيري طازجة.", size: "12 oz", nutrition: { fat: 55, carbs: 50, protein: 29, sugars: 24 }, allergens: ["dairy", "nuts", "gluten"] },
  30: { descEn: "Greek yogurt, chia, granola mix with strawberry.", descAr: "زبادي يوناني مع جرانولا مقرمشة وفراولة طازجة.", size: "12 oz", nutrition: { fat: 55, carbs: 48, protein: 26, sugars: 24 }, allergens: ["dairy", "nuts", "gluten"] },
  31: { descEn: "Fresh avocado guacamole dip with lime and cilantro.", descAr: "تغميسة جواكامولي أفوكادو طازج مع ليمون وكزبرة.", size: "12 oz", nutrition: { fat: 35, carbs: 18, protein: 5, sugars: 3 }, allergens: ["gluten"] },
  33: { descEn: "Creamy labneh mixed with lemon, zaatar — served with crackers.", descAr: "تغميسة لبنة تقليدية كريمية مع أعشاب.", size: "12 oz", nutrition: { fat: 30, carbs: 15, protein: 10, sugars: 3 }, allergens: ["gluten", "dairy", "sesame"] },
  34: { descEn: "Spicy jalapeno dip with a creamy base.", descAr: "تغميسة هالبينو حارة مع قاعدة كريمية.", size: "12 oz", nutrition: { fat: 30, carbs: 15, protein: 10, sugars: 3 }, allergens: ["dairy"] },
  35: { descEn: "Hummus with beetroot, tahini, lemon, olive oil — served with crackers.", descAr: "حمص شمندر نابض بالألوان مع طحينة وليمون.", size: "12 oz", nutrition: { fat: 20, carbs: 35, protein: 12, sugars: 5 }, allergens: ["gluten", "sesame"] },
  36: { descEn: "Hummus with avocado, tahini, lemon, olive oil — served with crackers.", descAr: "حمص كريمي ممزوج مع أفوكادو ناضج.", size: "12 oz", nutrition: { fat: 25, carbs: 28, protein: 12, sugars: 3 }, allergens: ["gluten", "sesame"] },
  37: { descEn: "Traditional hummus with tahini, lemon and olive oil — served with crackers.", descAr: "حمص كلاسيكي مع طحينة وليمون.", size: "12 oz", nutrition: { fat: 22, carbs: 30, protein: 14, sugars: 2 }, allergens: ["gluten", "sesame"] },
  38: { descEn: "Grilled halloumi cheese served with olives — a savoury plate.", descAr: "جبن حلومي مشوي مقدم مع زيتون — طبق مالح.", size: "12 oz", nutrition: { fat: 22, carbs: 8, protein: 18, sugars: 1 }, allergens: ["dairy"] },
  39: { descEn: "Crunchy baby cucumber pickles, tangy and refreshing.", descAr: "مخلل خيار صغير مقرمش، لاذع ومنعش.", size: "12 oz", nutrition: { fat: 0, carbs: 2, protein: 0.5, sugars: 1 }, allergens: [] },
  40: { descEn: "Assorted pickled vegetables — turnip, cucumber, carrot.", descAr: "مخللات خضار متنوعة — لفت، خيار، جزر.", size: "12 oz", nutrition: { fat: 0, carbs: 3, protein: 0.5, sugars: 1 }, allergens: [] },
  41: { descEn: "Spicy pickled peppers for the heat lovers.", descAr: "مخلل فلفل حار لعشاق الحرارة.", size: "12 oz", nutrition: { fat: 0.5, carbs: 4, protein: 1, sugars: 2 }, allergens: [] },
  42: { descEn: "100g crackers with whole grains.", descAr: "مقرمشات عالية البروتين، مثالية كوجبة خفيفة صحية.", size: "60 gm", nutrition: { fat: 6, carbs: 22, protein: 10, sugars: 0 }, allergens: ["gluten", "sesame"] },
  43: { descEn: "10 soft thyme bars.", descAr: "مقرمشات مقرمشة بنكهة الزعتر التقليدي.", size: "60 gm", nutrition: { fat: 5, carbs: 28, protein: 5, sugars: 0 }, allergens: ["gluten", "sesame"] },
  44: { descEn: "10 soft biscuits with thyme and dark chocolate.", descAr: "لمسة حلوة ومالحة: مقرمشات زعتر مع شوكولاتة.", size: "60 gm", nutrition: { fat: 6, carbs: 32, protein: 6, sugars: 0 }, allergens: ["gluten", "sesame"] },
  45: { descEn: "10 soft whole grain biscuits with dark chocolate, sugar-free.", descAr: "بسكويت شوكولاتة غني — حلوى مقرمشة وشهية.", size: "60 gm", nutrition: { fat: 10, carbs: 42, protein: 12, sugars: 0 }, allergens: ["gluten", "dairy"] },
  46: { descEn: "Traditional cake rusk — twice-baked for extra crunch.", descAr: "شابورة كيك تقليدية — مخبوزة مرتين لقرمشة إضافية.", size: "60 gm", nutrition: { fat: 10, carbs: 45, protein: 8, sugars: 0 }, allergens: ["gluten", "dairy", "eggs"] },
  47: { descEn: "Chocolate-dipped rusk fingers, crunchy and indulgent.", descAr: "أصابع شابورة مغطاة بالشوكولاتة، مقرمشة وشهية.", size: "60 gm", nutrition: { fat: 10, carbs: 42, protein: 12, sugars: 0 }, allergens: ["gluten", "dairy", "sesame"] },
  48: { descEn: "Crunchy corn snack.", descAr: "حبوب ذرة مقرمشة محمصة — وجبة خفيفة ومشبعة.", size: "60 gm", nutrition: { fat: 5, carbs: 30, protein: 6, sugars: 2 }, allergens: [] },
  49: { descEn: "Homemade fig jam with natural sweetness.", descAr: "مربى تين محلي الصنع بحلاوة طبيعية.", size: "150 ml", nutrition: { fat: 0.5, carbs: 45, protein: 1, sugars: 30 }, allergens: [] },
  50: { descEn: "Rich blueberry jam made with real berries.", descAr: "مربى بلوبيري غني مصنوع من توت حقيقي.", size: "150 ml", nutrition: { fat: 0.5, carbs: 48, protein: 1, sugars: 32 }, allergens: [] },
  51: { descEn: "Classic strawberry jam with fresh strawberries.", descAr: "مربى فراولة كلاسيكي مع فراولة طازجة.", size: "150 ml", nutrition: { fat: 0.5, carbs: 48, protein: 1, sugars: 32 }, allergens: [] },
  52: { descEn: "Vanilla cream, peanut butter, dark chocolate, sugar-free, 15g protein.", descAr: "نسخة صحية من سنيكرز الكلاسيكي — فول سوداني، كراميل وشوكولاتة.", size: "12 oz", nutrition: { fat: 55, carbs: 36, protein: 15, sugars: 24 }, allergens: ["peanuts", "dairy", "gluten"] },
  53: { descEn: "2 pieces sugar-free bars with 8g protein.", descAr: "بار بروتين أرز مقرمش — حلوى بدون ذنب.", size: "2 pcs", nutrition: { fat: 6, carbs: 22, protein: 10, sugars: 0 }, allergens: ["gluten"] },
  54: { descEn: "Coconut-flavoured protein bar — a tropical, guilt-free snack.", descAr: "بار بروتين بنكهة جوز الهند — وجبة خفيفة استوائية وصحية.", size: "2 pcs", nutrition: { fat: 8, carbs: 24, protein: 14, sugars: 5 }, allergens: ["gluten"] },
  55: { descEn: "Oats, nuts, peanut butter, protein powder.", descAr: "بار بروتين بنكهة زبدة الفول السوداني.", size: "2 pcs", nutrition: { fat: 6, carbs: 22, protein: 10, sugars: 0 }, allergens: ["gluten", "nuts", "peanuts"] },
  56: { descEn: "Sugar & trans-fat free caesar dressing.", descAr: "صوص سيزر كريمي — مثالي مع السلطات واللفائف.", size: "90 gm", nutrition: { fat: 28, carbs: 4, protein: 2, sugars: 1 }, allergens: ["dairy", "eggs"] },
  57: { descEn: "Sugar & trans-fat free herby green sauce.", descAr: "صوص أخضر بالأعشاب — طازج ولاذع.", size: "90 gm", nutrition: { fat: 26, carbs: 5, protein: 2, sugars: 1 }, allergens: [] },
  58: { descEn: "Sugar & trans-fat free avocado sauce.", descAr: "صوص أفوكادو ناعم — غني وكريمي.", size: "90 gm", nutrition: { fat: 16, carbs: 8, protein: 2, sugars: 1 }, allergens: [] },
  59: { descEn: "Savoury crab sauce — a seafood twist for any dish.", descAr: "صوص كراب لذيذ — لمسة بحرية لأي طبق.", size: "90 gm", nutrition: { fat: 6, carbs: 8, protein: 4, sugars: 2 }, allergens: ["shellfish"] },
  60: { descEn: "Sugar & trans-fat free Asian-inspired sauce.", descAr: "صوص آسيوي حلو ولاذع للتغميس.", size: "90 gm", nutrition: { fat: 12, carbs: 22, protein: 3, sugars: 8 }, allergens: ["soy"] },
  61: { descEn: "Lemon vinegar sauce.", descAr: "صوص خل خفيف — رفيق صحي للسلطة.", size: "90 gm", nutrition: { fat: 16, carbs: 6, protein: 1, sugars: 2 }, allergens: [] },
  62: { descEn: "Fresh ginger and lemon juice — a zesty, warming drink.", descAr: "عصير زنجبيل وليمون طازج — مشروب منعش ودافئ.", size: "330 ml", nutrition: { fat: 0, carbs: 28, protein: 1, sugars: 20 }, allergens: [] },
  63: { descEn: "Green apple, pineapple, spinach blend.", descAr: "مزيج منعش من الأوراق الخضراء والفواكه.", size: "330 ml", nutrition: { fat: 0.5, carbs: 26, protein: 2, sugars: 18 }, allergens: [] },
  64: { descEn: "Beetroot, carrot, orange blend.", descAr: "عصير شمندر طازج — نابض بالألوان ومغذي.", size: "330 ml", nutrition: { fat: 0, carbs: 30, protein: 3, sugars: 22 }, allergens: [] },
  65: { descEn: "Natural orange juice.", descAr: "عصير برتقال معصور طازج — نقي وطبيعي.", size: "330 ml", nutrition: { fat: 0, carbs: 36, protein: 2, sugars: 30 }, allergens: [] },
  66: { descEn: "Avocado, milk, peanut butter, protein.", descAr: "سموذي أفوكادو كريمي غني بالبروتين.", size: "330 ml", nutrition: { fat: 18, carbs: 35, protein: 25, sugars: 10 }, allergens: ["dairy", "peanuts"] },
  67: { descEn: "Dates, milk, peanut butter, protein.", descAr: "سموذي تمر غني بالبروتين — طاقة في كوب.", size: "330 ml", nutrition: { fat: 10, carbs: 50, protein: 28, sugars: 30 }, allergens: ["dairy", "peanuts"] },
  68: { descEn: "Zero-sugar cola — all the taste, none of the sugar.", descAr: "كولا بدون سكر — كل النكهة بدون سكر.", size: "330 ml", nutrition: { fat: 0, carbs: 0, protein: 0, sugars: 0 }, allergens: [] },
  69: { descEn: "Light cola — a lighter option for cola lovers.", descAr: "كولا لايت — خيار أخف لعشاق الكولا.", size: "330 ml", nutrition: { fat: 0, carbs: 0, protein: 0, sugars: 0 }, allergens: [] },
  70: { descEn: "Natural sparkling mineral water, 200ml.", descAr: "ماء معدنية غازية طبيعية.", size: "330 ml", nutrition: { fat: 0, carbs: 0, protein: 0, sugars: 0 }, allergens: [] },
  71: { descEn: "Pure still mineral water, 330ml.", descAr: "ماء معدنية نقية.", size: "330 ml", nutrition: { fat: 0, carbs: 0, protein: 0, sugars: 0 }, allergens: [] },
  72: { descEn: "100g chicken, 150g brown rice, 50g cottage cheese, mixed salad.", descAr: "دجاج مشوي مقدم مع أرز متبل.", size: "Plate", nutrition: { fat: 7.5, carbs: 1.7, protein: 36.5, sugars: 1.4 }, allergens: ["dairy"] },
  74: { descEn: "100g salmon, 150g brown rice, 50g cottage cheese, mix salad.", descAr: "فيليه سالمون مقلي مقدم مع أرز متبل.", size: "Plate", nutrition: { fat: 17, carbs: 36.5, protein: 31.8, sugars: 1.4 }, allergens: ["dairy", "fish"] },
  99: { descEn: "High protein tiramisu with greek yogurt, oats, chia, whole wheat biscuit, no added sugar.", descAr: "أوفرنايت أوتس بنكهة التيراميسو — قهوة، كاكاو وماسكربون.", size: "12 oz", nutrition: { fat: 6, carbs: 28, protein: 15.4, sugars: 9 }, allergens: ["dairy", "gluten"] },
  100: { descEn: "140g ground beef, brown rice 150g, special sauce, cottage cheese 50g.", descAr: "لحم بقري مفروم 140 جرام، رز بني 150 جرام، صوص خاص، جبن قريش 50 جرام.", size: "", nutrition: { fat: 13, carbs: 38, protein: 36, sugars: 1 }, allergens: ["dairy"] },
  101: { descEn: "Multigrain sourdough, burrata, arugula, sun-dried tomatoes, pesto, balsamic.", descAr: "خبز ساور حبوب خالي من السكر والدهون - بوراتا - جرجير - طماطم مجففة - بيستو - بلسمك.", size: "", nutrition: { fat: 12, carbs: 41, protein: 20, sugars: 0 }, allergens: ["dairy", "gluten"] },
  102: { descEn: "Egg mixture with avocado, dried tomato, arugula, sauce.", descAr: "خلطة بيض المسلوق اللذيذة مع جبن شيدر و افوكادو و طماطم مجففة و جرجير و صوص اباتاي.", size: "", nutrition: { fat: 17, carbs: 30, protein: 21, sugars: 7 }, allergens: ["eggs", "dairy", "gluten"] },
  103: { descEn: "Grilled chicken, tomato, avocado, cheese, chipotle sauce.", descAr: "دجاج مشوي - طماطم - افوكادو - جبن شيدر - صوص تشوبتلي.", size: "", nutrition: { fat: 20, carbs: 35, protein: 35, sugars: 2 }, allergens: ["gluten", "dairy", "nuts"] },
  104: { descEn: "10 pieces with 25g protein.", descAr: "١٠ قطع من عيدان بروتين بدقيق الحبه الكاملة مع الشوفان، يحتوي على 25 جرام بروتين.", size: "", nutrition: { fat: 6, carbs: 28, protein: 25, sugars: 3 }, allergens: ["gluten"] },
  105: { descEn: "High protein, chia, oats, cacao, whole grain biscuit, no added sugar.", descAr: "هاي بروتين - شيا - شوفان - كاكاو - بسكوت الحبه الكامله - بدون اضافة سكر.", size: "", nutrition: { fat: 7.5, carbs: 33, protein: 22, sugars: 10.5 }, allergens: ["gluten"] },
  106: { descEn: "High protein, chia, oats, cacao, whole grain biscuit, peanut butter, no added sugar.", descAr: "هاي بروتين - شيا - شوفان - كاكاو - بسكوت الحبه الكامله - فول سوداني - بدون اضافة سكر.", size: "", nutrition: { fat: 15, carbs: 35, protein: 24, sugars: 11 }, allergens: ["gluten", "nuts", "peanuts"] },
  107: { descEn: "Dark chocolate with 12g protein, peanuts, almonds.", descAr: "دارك شوكولاتة روكي رود مضاف له لوز وفول سوداني، تحتوي على 12 جرام بروتين.", size: "", nutrition: { fat: 12, carbs: 40, protein: 15, sugars: 0 }, allergens: ["nuts", "peanuts"] },
  108: { descEn: "Dark chocolate with whey protein, 8g protein.", descAr: "شوكولاتة داكنه مع وي بروتين 8 جرام.", size: "", nutrition: { fat: 6, carbs: 22, protein: 10, sugars: 0 }, allergens: ["dairy"] },
  109: { descEn: "3 protein brownie balls.", descAr: "3 قطع بروتين براونيز.", size: "", nutrition: { fat: 9, carbs: 20, protein: 12, sugars: 4 }, allergens: ["gluten"] },
}
